cript:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 1
  - node_modules/.bin/buster-server &
  - sleep 1
  - firefox http://localhost:1111/capture &
  - sleep 1
 
script:
  - "npm test"
 
language: node_js
 
node_js:
  - 0.8.x
